GOOGLE_API_KEY = "AQ.Ab8RN6K_gyWTxQbpGlpSj84zUgyF_qA0O0bdIRcJSRn6gexnSQ"
PINECONE_API_KEY = "pcsk_5uAuRL_D8i8yjTjnm3PUDCppwiasfzVdWzuFCcEgPkALMygYYoyNdCCjURofbgr3LDisNh"
PINECONE_INDEX = "rag-portfolio"